services:
  # nest-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest-api
  #   network_mode: host
  #   restart: always
  #   ports:
  #     - 3333:3333
  #   depends_on:
  #     - dcs-postgres
  #   env_file:
  #     - .env

  dcs-postgres:
    image: postgres:15.3-alpine
    container_name: dcs-postgres
    network_mode: host
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
