@baseURL = localhost
@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxNjQyNjk4MCwiZXhwIjoxNzE2NTEzMzgwfQ.9ViHF8V93qlsrpvavcnWMw9D7vAb2R2ilBSpuONyN6c

POST http://{{baseURL}}:3333/despesas
Authorization: {{authToken}}
Content-Type: application/json

{
  "nome": "Aluguel 2",
  "valorEstimado": 100,
  "usuarioCriou": 1,
  "dataPrevisao": 10,
  "empresaId": 1
}

###

GET http://{{baseURL}}:3333/despesas
Authorization: {{authToken}}
Content-Type: application/json

###

GET http://{{baseURL}}:3333/despesas?nome=i&empresaId=1
Authorization: {{authToken}}
Content-Type: application/json

###

DELETE http://{{baseURL}}:3333/despesas/3
Authorization: {{authToken}}
Content-Type: application/json

###

POST http://{{baseURL}}:3333/receitas
Authorization: {{authToken}}
Content-Type: application/json

{
  "nome": "receita qualquer",
  "valorEstimado": 1020,
  "usuarioCriou": 1,
  "dataPrevisao": 15,
  "empresaId": 2
}
###

GET http://{{baseURL}}:3333/receitas
Authorization: {{authToken}}
Content-Type: application/json

###
GET http://{{baseURL}}:3333/receitas?nome=rec&empresaId=2
Authorization: {{authToken}}
Content-Type: application/json

###

DELETE http://{{baseURL}}:3333/receitas/1
Authorization: {{authToken}}
Content-Type: application/json


###

POST http://{{baseURL}}:3333/lancamentos
Authorization: {{authToken}}
Content-Type: application/json

{
  "valor": 1700,
  "obs": "Aluguel facul 2",
  "recDesId": 6,
  "userId": 1,
  "empresaId": 2,
  "tipo": "D",
  "dataHora": "2024-05-23T02:06:38.845Z"
}

###

GET http://{{baseURL}}:3333/lancamentos
Authorization: {{authToken}}
Content-Type: application/json

###

GET http://{{baseURL}}:3333/usuarios
Content-Type: application/json

###
POST http://{{baseURL}}:3333/auth/login
Content-Type: application/json

{
  "email": "cachopaweb@gmail.com",
  "senha": "123456"
}

###
POST http://{{baseURL}}:3333/usuarios
Content-Type: application/json

{
   "nome": "Alessandro",
   "email": "cachopaweb@gmail.com",
   "senha": "123456",
   "admin": true
}

###
POST http://{{baseURL}}:3333/empresas
Content-Type: application/json

{
   "nome": "PORTAL DOS ANJOS 2"
}


###
GET http://{{baseURL}}:3333/empresas
Content-Type: application/json

###
GET http://{{baseURL}}:3333/movimentacoes
Content-Type: application/json

###
GET http://{{baseURL}}:3333/movimentacoes?empresaId=2
Content-Type: application/json