POST http://localhost:3000/despesas
Content-Type: application/json

{
    "nome": "ENERGIA UNIDADE 1",
    "valorEstimado": 2600
}

###

GET http://localhost:3000/despesas
Content-Type: application/json

###

POST http://localhost:3000/lancamentos
Content-Type: application/json

{
    "obs": "teste de lancamento 2",
    "despesaId": 2,
    "valor": 2900
}

###

GET http://localhost:3000/lancamentos
Content-Type: application/json